### ISSUE TITLE
Suggestion: blur improvements.

### ISSUE THREAD

**Issue by barolo** [CDrummond/lms-material#869]
Would you consider improving how blur looks?

Currently it gets messed up at the edges: 
![Screenshot_20240413_141621](https://github.com/CDrummond/lms-material/assets/1215421/6a929452-3186-4537-9399-0f83a9ddcc2a)

After tweaking it a bit: 
![Screenshot_20240413_141539](https://github.com/CDrummond/lms-material/assets/1215421/25e07240-b780-4a64-b8b4-c1cb94433dc2)

My haphazard solution was to stretch the width/height of bg cover  to 105% and move margins -10
also replaced dimming with shadow with css filter instead:

```css
.np-bgnd-cover {
    -webkit-filter: none;
    box-shadow: none;
    filter: blur(10px) brightness(26%) ;
}
.np-bgnd {
   margin:-10px;
	width: 105%;
	height: 105%;
}
```
